const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);

// Keep every activation-code field in sync with the target page's plain text input behavior.
const activationFields=$$('#code,#global-code,#qr-code,#order-id');
const key=new URLSearchParams(window.location.search).get('key');
if(key) activationFields.forEach(field=>{field.value=key;});

$('#tabs').addEventListener('click',e=>{const li=e.target.closest('li');if(!li)return;$$('.layui-tab-title li').forEach(x=>x.classList.remove('layui-this'));li.classList.add('layui-this');$$('.layui-tab-item').forEach(x=>x.classList.toggle('layui-show',x.dataset.panel===li.dataset.tab))});
$('#redeem-form').addEventListener('submit',async e=>{e.preventDefault();const msg=$('#form-message'),code=$('#code').value.trim(),uid=$('#player-id').value.trim();if(code.length<12||uid.length<3){msg.textContent='请输入完整激活码和 Steam 账号。';return}$('#progress-steam').style.display='block';$('#progress-bar').style.width='35%';msg.textContent='正在处理...';try{const r=await fetch('/api/redeem',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,player_id:uid,player_name:$('#player-name').value.trim()})});const d=await r.json();$('#progress-bar').style.width=r.ok?'100%':'0%';msg.textContent=d.message;if(d.order_id){$('#order-id').value=d.order_id;$('#steam-content').textContent=`订单号：${d.order_id} · 状态：${d.status}`}}catch{msg.textContent='后端服务未启动，请运行 python server.py。'}});$('#check-order-short').addEventListener('click',()=>{$('[data-tab="orders"]').click()});$('#query-order').addEventListener('click',async()=>{const id=$('#order-id').value.trim(),out=$('#order-result');if(!id){out.textContent='请输入订单编号。';return}try{const r=await fetch('/api/orders/'+encodeURIComponent(id)),d=await r.json();out.textContent=d.message||`${d.status} · ${d.reward}`}catch{out.textContent='查询失败，请确认后端已启动。'}});$('#generate-qr').addEventListener('click',()=>{if(!$('#qr-code').value.trim()){$('#qr-result').textContent='请输入激活码。';return}$('#qr-box').style.display='block';$('#qr-result').textContent='二维码已生成，请使用对应客户端扫码。'});
